require File.expand_path('../boot', __FILE__)

# Pick the frameworks you want:
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "active_resource/railtie"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end

module Wb10
  class Application < Rails::Application

    require 'rack/rewrite'

    config.middleware.insert_before(Rack::Lock, Rack::Rewrite) do
      # example rewrites
      # rewrite '/wiki/John_Trupiano', '/john'
      
         r301 '/news/', '/news'
         r301 '/why-wieser-brothers/', '/our-commitment'
         r301 '/why-wieser-brothers-main/', '/our-commitment'
         r301 '/about-us-bios/', '/our-firm'
         r301 '/testimonials/', '/projects'
         r301 '/services/', '/our-services'
         r301 '/current-projects/', '/projects'
         r301 '/agropur/', '/projects'
         r301 '/ivy-lace-building-onalaska/', '/projects'
         r301 '/kwik-trip-bakery-freezer-la/', '/projects'
         r301 '/kwik-trip-dairy-intake-bay-l/', '/projects'
         r301 '/mt-borah-coon-valley-wi/', '/projects'
         r301 '/organic-valley-cashton-office/', '/projects'
         r301 '/viroqua-public-library/', '/projects'
         r301 '/wieser-concrete-maiden-rock/', '/projects'
         r301 '/wieser-concrete-menomonie-wi/', '/projects'
         r301 '/wtc-integrated-tech-center-l/', '/projects'
         r301 '/wtc-coleman-center-la-crosse/', '/projects'
         r301 '/projects-completed/', '/projects'
         r301 '/aw-restaurant/', '/projects'
         r301 '/able/', '/projects'
         r301 '/allergy-associates-of-la-cross/', '/projects'
         r301 '/altra-federal-credit-union/', '/projects'
         r301 '/altra-federal-credit-union-w/', '/projects'
         r301 '/altra-operations-center-expans/', '/projects'
         r301 '/amerhart-ltd/', '/projects'
        r301 '/badger-corrugating/', '/projects'
        r301 '/bakalars-la-crosse-wi/', '/projects'
        r301 '/brownsville-maintenance-buildi/', '/projects'
        r301 '/breidenbach-chiropractic-la/', '/projects'
        r301 '/bremer-bank/', '/projects'
        r301 '/cashton-community-hall/', '/projects'
        r301 '/cargill-office-addition-la-c/', '/projects'
        r301 '/cedar-valley-resort/', '/projects'
        r301 '/childrens-treehouse/', '/projects'
        r301 '/chippewa-calfs/', '/projects'
        r301 '/coulee-cap/', '/projects'
        r301 '/creative-screen-print/', '/projects'
        r301 '/creekside-business-center/', '/projects'
        r301 '/fj-robers/', '/projects'
        r301 '/gays-mills-mercantile-building/', '/projects'
        r301 '/gundersen-lutheran-clinic-la/', '/projects'
        r301 '/gundersen-lutheran-ortho-remod/', '/projects'
        r301 '/harborview/', '/projects'
        r301 '/hawkeye-rural-electric-coopera/', '/projects'
        r301 '/ho-chunk-nation-bia-roads/', '/projects'
        r301 '/hillview-rcac/', '/projects'
        r301 '/holy-family-education-center/', '/projects'
        r301 '/houghtons/', '/projects'
        r301 '/houston-county-justice-center/', '/projects'
        r301 '/kwik-trip-alternative-fuel-isl/', '/projects'
        r301 '/kwik-trip-bakery/', '/projects'
        r301 '/kwik-trip-bakery2/', '/projects'
        r301 '/kwik-trip-clinic-and-health-ce/', '/projects'
        r301 '/kwik-trip-commissary/', '/projects'
        r301 '/kwik-trip-dairy/', '/projects'
        r301 '/kwik-trip-dairy-engine-room/', '/projects'
        r301 '/kwik-trip-freezer-addition/', '/projects'
        r301 '/kwik-trip-ice-cream/', '/projects'
        r301 '/kwik-trip-ice-plant/', '/projects'
        r301 '/-kwik-trip-waupaca-wi-store/', '/projects'
        r301 '/lb-white/', '/projects'
        r301 '/lha-schuh-homes-duplexes/', '/projects'
        r301 '/little-minds-learning-center/', '/projects'
        r301 '/little-minds-oakdale-mn/', '/projects'
        r301 '/little-minds-daycare-onalask/', '/projects'
        r301 '/little-minds-daycare-river-f/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/', '/projects'
        r301 '/marshfield-food-safety-auror/', '/projects'
        r301 '/marshfield-food-safety-frion/', '/projects'
        r301 '/marshfield-food-safety-hende/', '/projects'
        r301 '/marshfield-food-safety-high/', '/projects'
        r301 '/marshfield-food-safety-leips/', '/projects'
        r301 '/marshfield-food-safety-plain/', '/projects'
        r301 '/marshfield-food-safety-willm/', '/projects'
        r301 '/metropolitan-market-place-ro/', '/projects'
        r301 '/miracle-league-field/', '/projects'
        r301 '/morrow-memorial-home/', '/projects'
        r301 '/northeast-iowa-community-colle/', '/projects'
        r301 '/organic-valley-head-quarters/', '/projects'
        r301 '/organic-valley-headquarters-ph/', '/projects'
        r301 '/organic-valley/', '/projects'
        r301 '/organic-valley-produce-hills/', '/projects'
        r301 '/pepsi-cola-bottling-co/', '/projects'
        r301 '/pepsi-cola-bottling-of-la-cros/', '/projects'
        r301 '/peterson-wastewater-treatment/', '/projects'
        r301 '/river-steel/', '/projects'
        r301 '/robers-cottonseed-building/', '/projects'
        r301 '/our-lady-of-shrine-of-guadalup/', '/projects'
        r301 '/specialty-foods/', '/projects'
        r301 '/star-blends-feed-mill-sparta/', '/projects'
        r301 '/st-joseph-equipment/', '/projects'
        r301 '/subway-winona-mn/', '/projects'
        r301 '/town-of-greenfield/', '/projects'
        r301 '/tri-county-electric/', '/projects'
        r301 '/unimin-mine/', '/projects'
        r301 '/university-falls-east/', '/projects'
        r301 '/university-falls-west/', '/projects'
        r301 '/van-riper-park-shelter/', '/projects'
        r301 '/vernon-economic-development/', '/projects'
        r301 '/vernon-electric-cooperative/', '/projects'
        r301 '/warner-laundry/', '/projects'
        r301 '/westby-coop-creamery-cooler/', '/projects'
        r301 '/whitehall-specialties/', '/projects'
        r301 '/wieser-brothers-addition/', '/projects'
        r301 '/wtc-diesel-tech-la-crosse-wi/', '/projects'
        r301 '/wtc-kumm-center-site-development/', '/projects'
        r301 '/project-picture-pages/', '/projects'
        r301 '/education/', '/projects'
        r301 '/financial/', '/projects'
        r301 '/food-processing/', '/projects'
        r301 '/healthcare/', '/projects'
        r301 '/laboratories/', '/projects'
        r301 '/manufacturing/', '/projects'
        r301 '/multi-tenant/', '/projects'
        r301 '/office/', '/projects'
        r301 '/religious/', '/projects'
        r301 '/restaurant/', '/projects'
        r301 '/residential/', '/projects'
        r301 '/retail/', '/projects'
        r301 '/warehouse/', '/projects'
        r301 '/affiliations-links/', '/projects'
        r301 '/bid-opportunities/', '/projects'
        r301 '/employment-opportunities/', '/projects'
        r301 '/carpenters-concrete-finishers/', '/projects'
        r301 '/contact-us/', '/projects'
        r301 '/news/2014/7/11/wieser-brothers-maintains-a-community-minded-culture.html', '/news'
        r301 '/display/ShowJournal?moduleId=751384&creatorId=99363', '/news'
        r301 '/news/2014/6/12/wieser-brothers-congratulates-five-leed-green-associate-prof.html', '/news'
        r301 '/news/2014/6/12/cedar-valley-resort-now-open.html', '/news'
        r301 '/news/2014/3/31/wieser-brothers-celebrates-20-years-of-business.html', '/news'
        r301 '/news/2014/3/13/dale-carnegie-course-graduate.html', '/news'
        r301 '/news/?currentPage=2', '/news'
        r301 '/news/?currentPage=3', '/news'
        r301 '/agropur/october-2014-update/', '/projects'
        r301 '/agropur/september-2014-update/', '/projects'
        r301 '/agropur/august-2014-update/', '/projects'
        r301 '/ivy-lace-building-onalaska/october-2014-update/', '/projects'
        r301 '/ivy-lace-building-onalaska/september-2014-update/', '/projects'
        r301 '/ivy-lace-building-onalaska/august-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/october-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/september-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/august-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/july-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/june-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/may-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/march-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/february-2014-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/december-2013-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/november-2013-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/september-2013-update/', '/projects'
        r301 '/kwik-trip-bakery-freezer-la/june-2013-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/october-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/august-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/july-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/june-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/may-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/april-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/march-2014-update/', '/projects'
        r301 '/kwik-trip-dairy-intake-bay-l/february-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/october-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/september-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/august-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/july-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/june-2014-update/', '/projects'
        r301 '/mt-borah-coon-valley-wi/may-2014-groundbreaking/', '/projects'
        r301 '/organic-valley-cashton-office/october-2014-update/', '/projects'
        r301 '/organic-valley-cashton-office/september-2013-update/', '/projects'
        r301 '/organic-valley-cashton-office/july-2013-update/', '/projects'
        r301 '/organic-valley-cashton-office/june-2013-update/', '/projects'
        r301 '/organic-valley-cashton-office/may-2013-update/', '/projects'
        r301 '/viroqua-public-library/october-2014-update/', '/projects'
        r301 '/viroqua-public-library/september-2014-update/', '/projects'
        r301 '/viroqua-public-library/august-2014-update/', '/projects'
        r301 '/viroqua-public-library/july-2014-update/', '/projects'
        r301 '/viroqua-public-library/june-2014-update/', '/projects'
        r301 '/wieser-concrete-maiden-rock/october-2014-update/', '/projects'
        r301 '/wieser-concrete-menomonie-wi/september-2014-update/', '/projects'
        r301 '/wieser-concrete-menomonie-wi/august-2014-update/', '/projects'
        r301 '/wieser-concrete-menomonie-wi/july-2014-update/', '/projects'
        r301 '/wtc-integrated-tech-center-l/october-2014-update/', '/projects'
        r301 '/wtc-integrated-tech-center-l/august-2014-update/', '/projects'
        r301 '/wtc-coleman-center-la-crosse/september-2014-update/', '/projects'
        r301 '/wtc-coleman-center-la-crosse/august-2014-update/', '/projects'
        r301 '/aw-restaurant/interior/', '/projects'
        r301 '/aw-restaurant/exterior/', '/projects'
        r301 '/able/interior/', '/projects'
        r301 '/able/exterior/', '/projects'
        r301 '/allergy-associates-of-la-cross/exterior/', '/projects'
        r301 '/altra-federal-credit-union/interior/', '/projects'
        r301 '/altra-federal-credit-union/exterior/', '/projects'
        r301 '/altra-federal-credit-union-w/july-2013-update/', '/projects'
        r301 '/altra-federal-credit-union-w/may-2013-update/', '/projects'
        r301 '/altra-operations-center-expans/september-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/august-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/july-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/june-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/may-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/april-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/march-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/february-2012-update/', '/projects'
        r301 '/altra-operations-center-expans/trusses-begin-january-2012/', '/projects'
        r301 '/altra-operations-center-expans/work-in-progress/', '/projects'
        r301 '/altra-operations-center-expans/exterior/', '/projects'
        r301 '/amerhart-ltd/interior/', '/projects'
        r301 '/amerhart-ltd/exterior/', '/projects'
        r301 '/badger-corrugating/may-2013-update/', '/projects'
        r301 '/bakalars-la-crosse-wi/march-2013-update/', '/projects'
        r301 '/bakalars-la-crosse-wi/february-2013-update/', '/projects'
        r301 '/bakalars-la-crosse-wi/december-2012-update/', '/projects'
        r301 '/bakalars-la-crosse-wi/october-2012-update/', '/projects'
        r301 '/brownsville-maintenance-buildi/august-2014-update/', '/projects'
        r301 '/breidenbach-chiropractic-la/may-2013-update/', '/projects'
        r301 '/breidenbach-chiropractic-la/march-2013-update/', '/projects'
        r301 '/breidenbach-chiropractic-la/january-2013-update/', '/projects'
        r301 '/breidenbach-chiropractic-la/november-2012-update/', '/projects'
        r301 '/bremer-bank/july-2014-update/', '/projects'
        r301 '/bremer-bank/june-2014-update/', '/projects'
        r301 '/bremer-bank/may-2014-update/', '/projects'
        r301 '/bremer-bank/april-2014-update/', '/projects'
        r301 '/bremer-bank/march-2014-update/', '/projects'
        r301 '/bremer-bank/february-2014-update/', '/projects'
        r301 '/bremer-bank/january-2014-update/', '/projects'
        r301 '/cashton-community-hall/building-addition/', '/projects'
        r301 '/cargill-office-addition-la-c/may-2013-update/', '/projects'
        r301 '/cedar-valley-resort/exterior/', '/projects'
        r301 '/cedar-valley-resort/interior/', '/projects'
        r301 '/childrens-treehouse/interior/', '/projects'
        r301 '/childrens-treehouse/exterior/', '/projects'
        r301 '/chippewa-calfs/exterior/', '/projects'
        r301 '/chippewa-calfs/arial-photos/', '/projects'
        r301 '/coulee-cap/exterior/', '/projects'
        r301 '/creative-screen-print/exterior/', '/projects'
        r301 '/creekside-business-center/completed-november-2011/', '/projects'
        r301 '/fj-robers/may-2012-update/', '/projects'
        r301 '/fj-robers/april-2012-update/', '/projects'
        r301 '/gays-mills-mercantile-building/nearing-completion-november-2011/', '/projects'
        r301 '/gays-mills-mercantile-building/new-building/', '/projects'
        r301 '/gundersen-lutheran-clinic-la/exterior/', '/projects'
        r301 '/gundersen-lutheran-ortho-remod/september-2012-update/', '/projects'
        r301 '/gundersen-lutheran-ortho-remod/august-2012-update/', '/projects'
        r301 '/gundersen-lutheran-ortho-remod/july-2012-update/', '/projects'
        r301 '/harborview/demolition/', '/projects'
        r301 '/hawkeye-rural-electric-coopera/interior/', '/projects'
        r301 '/hawkeye-rural-electric-coopera/exterior/', '/projects'
        r301 '/hawkeye-rural-electric-coopera/existing-and-demolition/', '/projects'
        r301 '/ho-chunk-nation-bia-roads/building-addition/', '/projects'
        r301 '/hillview-rcac/completed-december-2011/', '/projects'
        r301 '/hillview-rcac/interior/', '/projects'
        r301 '/hillview-rcac/exterior/', '/projects'
        r301 '/holy-family-education-center/interior/', '/projects'
        r301 '/holy-family-education-center/exterior/', '/projects'
        r301 '/houghtons/interior/', '/projects'
        r301 '/houghtons/exterior/', '/projects'
        r301 '/houston-county-justice-center/concrete-work/', '/projects'
        r301 '/kwik-trip-alternative-fuel-isl/completed-project/', '/projects'
        r301 '/kwik-trip-alternative-fuel-isl/february-2012-update/', '/projects'
        r301 '/kwik-trip-alternative-fuel-isl/work-in-progress-december-2011/', '/projects'
        r301 '/kwik-trip-bakery/interior/', '/projects'
        r301 '/kwik-trip-bakery/exterior/', '/projects'
        r301 '/kwik-trip-bakery2/february-2012-update/', '/projects'
        r301 '/kwik-trip-bakery2/work-begins-november-2011/', '/projects'
        r301 '/kwik-trip-clinic-and-health-ce/october-2013-update/', '/projects'
        r301 '/kwik-trip-clinic-and-health-ce/september-2013-update/', '/projects'
        r301 '/kwik-trip-commissary/finished-pictures-before-equipment-was-in-place/', '/projects'
        r301 '/kwik-trip-commissary/interior/', '/projects'
        r301 '/kwik-trip-commissary/exterior/', '/projects'
        r301 '/kwik-trip-commissary/groundbreaking-pictures-june-26-2006/', '/projects'
        r301 '/kwik-trip-dairy/august-2014-update/', '/projects'
        r301 '/kwik-trip-dairy/may-2014-update/', '/projects'
        r301 '/kwik-trip-dairy/march-2014-update/', '/projects'
        r301 '/kwik-trip-dairy/november-2013-update/', '/projects'
        r301 '/kwik-trip-dairy/july-2013-update/', '/projects'
        r301 '/kwik-trip-dairy/june-2013-update/', '/projects'
        r301 '/kwik-trip-dairy/may-2013-update/', '/projects'
        r301 '/kwik-trip-dairy/march-2013-update/', '/projects'
        r301 '/kwik-trip-dairy-engine-room/exterior/', '/projects'
        r301 '/kwik-trip-freezer-addition/august-2012-update/', '/projects'
        r301 '/kwik-trip-freezer-addition/july-2012-update/', '/projects'
        r301 '/kwik-trip-freezer-addition/april-2012-update/', '/projects'
        r301 '/kwik-trip-freezer-addition/march-2012-update/', '/projects'
        r301 '/kwik-trip-freezer-addition/february-2012-update/', '/projects'
        r301 '/kwik-trip-freezer-addition/progress-photos/', '/projects'
        r301 '/kwik-trip-ice-cream/april-2012-update/', '/projects'
        r301 '/kwik-trip-ice-cream/march-2012-update/', '/projects'
        r301 '/kwik-trip-ice-cream/february-2012-update/', '/projects'
        r301 '/kwik-trip-ice-cream/work-begins-october-2011/', '/projects'
        r301 '/kwik-trip-ice-plant/interior/', '/projects'
        r301 '/kwik-trip-ice-plant/exterior/', '/projects'
        r301 '/-kwik-trip-waupaca-wi-store/september-2012-update/', '/projects'
        r301 '/-kwik-trip-waupaca-wi-store/august-2012-update/', '/projects'
        r301 '/lb-white/interior/', '/projects'
        r301 '/lb-white/exterior/', '/projects'
        r301 '/lha-schuh-homes-duplexes/interior/', '/projects'
        r301 '/lha-schuh-homes-duplexes/exterior/', '/projects'
        r301 '/little-minds-learning-center/may-2014-update/', '/projects'
        r301 '/little-minds-learning-center/april-2014-update/', '/projects'
        r301 '/little-minds-learning-center/march-2014-update/', '/projects'
        r301 '/little-minds-learning-center/february-2014-update/', '/projects'
        r301 '/little-minds-oakdale-mn/june-2013-update/', '/projects'
        r301 '/little-minds-oakdale-mn/may-2013-update/', '/projects'
        r301 '/little-minds-oakdale-mn/march-2013-update/', '/projects'
        r301 '/little-minds-oakdale-mn/february-2013-update/', '/projects'
        r301 '/little-minds-oakdale-mn/january-2013-update/', '/projects'
        r301 '/little-minds-oakdale-mn/november-2012-update/', '/projects'
        r301 '/little-minds-daycare-onalask/completed-november-2011/', '/projects'
        r301 '/little-minds-daycare-onalask/exterior/', '/projects'
        r301 '/little-minds-daycare-river-f/completed-august-2011/', '/projects'
        r301 '/little-minds-daycare-river-f/exterior/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/may-2013-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/march-2013-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/february-2013-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/january-2013-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/november-2012-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/october-2012-update/', '/projects'
        r301 '/-lorentz-meats-cannon-falls-m/september-2012-update/', '/projects'
        r301 '/marshfield-food-safety-auror/interior/', '/projects'
        r301 '/marshfield-food-safety-auror/exterior/', '/projects'
        r301 '/marshfield-food-safety-frion/exterior-interior/', '/projects'
        r301 '/marshfield-food-safety-hende/interior/', '/projects'
        r301 '/marshfield-food-safety-hende/exterior/', '/projects'
        r301 '/marshfield-food-safety-high/exterior-interior/', '/projects'
        r301 '/marshfield-food-safety-leips/exterior-interior/', '/projects'
        r301 '/marshfield-food-safety-plain/exterior-interior/', '/projects'
        r301 '/marshfield-food-safety-willm/may-2012-update/', '/projects'
        r301 '/marshfield-food-safety-willm/march-2012-progress/', '/projects'
        r301 '/metropolitan-market-place-ro/june-2013-update/', '/projects'
        r301 '/metropolitan-market-place-ro/may-2013-update/', '/projects'
        r301 '/metropolitan-market-place-ro/march-2013-update/', '/projects'
        r301 '/metropolitan-market-place-ro/september-2012-update/', '/projects'
        r301 '/metropolitan-market-place-ro/august-2012-update/', '/projects'
        r301 '/metropolitan-market-place-ro/july-2012-update/', '/projects'
        r301 '/metropolitan-market-place-ro/june-2012-update/', '/projects'
        r301 '/metropolitan-market-place-ro/may-2012-update/', '/projects'
        r301 '/miracle-league-field/field/', '/projects'
        r301 '/morrow-memorial-home/interior/', '/projects'
        r301 '/morrow-memorial-home/exterior/', '/projects'
        r301 '/morrow-memorial-home/ground-breaking-april-2010/', '/projects'
        r301 '/northeast-iowa-community-colle/exterior/', '/projects'
        r301 '/organic-valley-head-quarters/fallwinter-2011-12-work/', '/projects'
        r301 '/organic-valley-head-quarters/interior/', '/projects'
        r301 '/organic-valley-head-quarters/exterior/', '/projects'
        r301 '/organic-valley-headquarters-ph/march-2014-update/', '/projects'
        r301 '/organic-valley/finished-photos/', '/projects'
        r301 '/organic-valley/pictures-from-pour-on-8-30-06/', '/projects'
        r301 '/organic-valley/second-pour-9-21-06/', '/projects'
        r301 '/organic-valley/exterior/', '/projects'
        r301 '/organic-valley/interior/', '/projects'
        r301 '/organic-valley-produce-hills/august-2012-completed-photos/', '/projects'
        r301 '/organic-valley-produce-hills/july-2012-update/', '/projects'
        r301 '/organic-valley-produce-hills/june-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/august-2012-completed-pictures/', '/projects'
        r301 '/pepsi-cola-bottling-co/july-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/june-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/may-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/april-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/march-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/february-2012-update/', '/projects'
        r301 '/pepsi-cola-bottling-co/work-begins/', '/projects'
        r301 '/pepsi-cola-bottling-co/may-22-2011-tornado-hits-la-crosse/', '/projects'
        r301 '/pepsi-cola-bottling-of-la-cros/exterior/', '/projects'
        r301 '/peterson-wastewater-treatment/exterior/', '/projects'
        r301 '/river-steel/interior/', '/projects'
        r301 '/river-steel/exterior/', '/projects'
        r301 '/robers-cottonseed-building/completed-november-2011/', '/projects'
        r301 '/robers-cottonseed-building/exterior/', '/projects'
        r301 '/our-lady-of-shrine-of-guadalup/exterior/', '/projects'
        r301 '/our-lady-of-shrine-of-guadalup/interior/', '/projects'
        r301 '/specialty-foods/interior/', '/projects'
        r301 '/specialty-foods/exterior/', '/projects'
        r301 '/star-blends-feed-mill-sparta/august-2014-update/', '/projects'
        r301 '/star-blends-feed-mill-sparta/july-2014-update/', '/projects'
        r301 '/star-blends-feed-mill-sparta/june-2014-update/', '/projects'
        r301 '/star-blends-feed-mill-sparta/may-2014-update/', '/projects'
        r301 '/star-blends-feed-mill-sparta/march-2014-update/', '/projects'
        r301 '/star-blends-feed-mill-sparta/february-2014-update/', '/projects'
        r301 '/st-joseph-equipment/interior/', '/projects'
        r301 '/st-joseph-equipment/exterior/', '/projects'
        r301 '/subway-winona-mn/july-2013-update/', '/projects'
        r301 '/subway-winona-mn/june-2013-update/', '/projects'
        r301 '/subway-winona-mn/may-2013-update/', '/projects'
        r301 '/town-of-greenfield/exterior/', '/projects'
        r301 '/tri-county-electric/interior/', '/projects'
        r301 '/tri-county-electric/exterior/', '/projects'
        r301 '/university-falls-east/exterior-interior/', '/projects'
        r301 '/university-falls-west/project-completed-june-2012-update/', '/projects'
        r301 '/university-falls-west/may-2012-update/', '/projects'
        r301 '/university-falls-west/april-2012-update/', '/projects'
        r301 '/university-falls-west/march-2012-update/', '/projects'
        r301 '/university-falls-west/february-2012-update/', '/projects'
        r301 '/university-falls-west/work-begins-november-2011/', '/projects'
        r301 '/van-riper-park-shelter/progress-pictures/', '/projects'
        r301 '/vernon-economic-development/susan-noble-veda-executive-director-recieves-recognition-fro/', '/projects'
        r301 '/vernon-economic-development/sue-noble-veda-executive-director-pics/', '/projects'
        r301 '/vernon-economic-development/may-2012-update/', '/projects'
        r301 '/vernon-economic-development/april-2012-update/', '/projects'
        r301 '/vernon-economic-development/march-2012-update/', '/projects'
        r301 '/vernon-economic-development/february-2012-update/', '/projects'
        r301 '/vernon-electric-cooperative/interior/', '/projects'
        r301 '/vernon-electric-cooperative/exterior/', '/projects'
        r301 '/warner-laundry/interior/', '/projects'
        r301 '/warner-laundry/exterior/', '/projects'
        r301 '/westby-coop-creamery-cooler/march-2012-update/', '/projects'
        r301 '/westby-coop-creamery-cooler/february-2012-update/', '/projects'
        r301 '/westby-coop-creamery-cooler/january-2012/', '/projects'
        r301 '/westby-coop-creamery-cooler/work-begins/', '/projects'
        r301 '/whitehall-specialties/interior/', '/projects'
        r301 '/whitehall-specialties/exterior/', '/projects'
        r301 '/wieser-brothers-addition/july-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/june-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/may-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/april-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/march-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/february-2012-update/', '/projects'
        r301 '/wieser-brothers-addition/project-starts-december-2011/', '/projects'
        r301 '/wtc-diesel-tech-la-crosse-wi/september-2013-update/', '/projects'
        r301 '/wtc-kumm-center-site-developme/site-work/', '/projects'
        r301 '/storage/Crucifixion%20School%209-12-07.pdf', '/projects'
        r301 '/storage/project-pages/first%20evangelical%20lutheran%20school.pdf', '/projects'
        r301 '/storage/project-pages/ona%20luther%20high%20school%202-15-05.pdf', '/projects'
        r301 '/storage/Altra%20Federal%20Credit%20Union%20-%20Holmen%203-3-10.pdf', '/projects'
        r301 '/storage/Altra%20Federal%20Credit%20Union%20-%20Winona%201-8-09.pdf', '/projects'
        r301 '/storage/project-pages/altra%20trane%20federal%20credit%20union.pdf', '/projects'
        r301 '/storage/project-pages/merchant%27s%20bank%20-%20la%20crescent.pdf', '/projects'
        r301 '/storage/project-pages/merchant%27s%20bank-%20onalaska.pdf', '/projects'
        r301 '/storage/KT%20Commissary.pdf', '/projects'
        r301 '/storage/Kwik%20Trip%20Ice%20Plant%202-13-09.pdf', '/projects'
        r301 '/storage/KT%20Distribution.pdf', '/projects'
        r301 '/storage/Organic%20Valley.pdf', '/projects'
        r301 '/storage/Main%20Street%20Ingredients%20Lab%20addition%202.pdf', '/projects'
        r301 '/storage/Allergy%20Associates%20of%20La%20Crosse%206-29-11.pdf', '/projects'
        r301 '/storage/Gundersen%20Lutheran%20La%20Crescent%20Clinic.pdf', '/projects'
        r301 '/storage/Gundersen%20Lutheran%203rd%20Floor%20Remodel.pdf', '/projects'
        r301 '/storage/Franciscan%20Skemp%204th%20Floor%20Remodel.pdf', '/projects'
        r301 '/storage/project-pages/bronston.pdf', '/projects'
        r301 '/storage/project-pages/cowgill%20dental.pdf', '/projects'
        r301 '/storage/project-pages/family%20vision%20center.pdf', '/projects'
        r301 '/storage/project-pages/Main%20Street%20Ingredients%20Lab%20addition%202.pdf', '/projects'
        r301 '/storage/project-pages/Kwik%20Trip%20Test%20Lab.pdf', '/projects'
        r301 '/storage/project-pages/River%20Steel%202-7-08.pdf', '/projects'
        r301 '/storage/project-pages/advanced%20fiber%20products.pdf', '/projects'
        r301 '/storage/project-pages/emerald%20hardwoods.pdf', '/projects'
        r301 '/storage/project-pages/skipperliner%20ext%20and%20int.pdf', '/projects'
        r301 '/storage/ABLE%20La%20Crescent%207-7-10.pdf', '/projects'
        r301 '/storage/project-pages/cedar%20valley%202-3-05.pdf', '/projects'
        r301 '/storage/Dietrich%20Condos%201-8-09.pdf', '/projects'
        r301 '/storage/project-pages/pine%20ridge%20apartments.pdf', '/projects'
        r301 '/storage/Walnut%20Street%20Building%2011-5-09.pdf', '/projects'
        r301 '/storage/Century%20Expo.pdf', '/projects'
        r301 '/storage/project-pages/fitzpatricks%20law%20office.pdf', '/projects'
        r301 '/storage/IC%20System%20Center%2090%20Buildout%209-14-09.pdf', '/projects'
        r301 '/storage/project-pages/jf%20brennan.pdf', '/projects'
        r301 '/storage/project-pages/midwest%20offices%20%202-2-05.pdf', '/projects'
        r301 '/storage/Pepsi-Cola%20of%20La%20Crosse%208-2012.pdf', '/projects'
        r301 '/storage/Crucifixion%20Church%20Restoration%209-14-07.pdf', '/projects'
        r301 '/storage/First%20Evangelical%20Lutheran%20Church%208-4-09.pdf', '/projects'
        r301 '/storage/Shrine%20of%20Guadalupe%203-3-10.pdf', '/projects'
        r301 '/storage/Checkers%209-14-09.pdf', '/projects'
        r301 '/storage/project-pages/manny%27s%20int%20and%20ext.pdf', '/projects'
        r301 '/storage/project-pages/Burrachos%201-11-06.pdf', '/projects'
        r301 '/storage/Binsfeld%20Residence%203-11-08.pdf', '/projects'
        r301 '/storage/Bukacek%20Residence%201-15-09.pdf', '/projects'
        r301 '/storage/Schini%20Residence.pdf', '/projects'
        r301 '/storage/All%20Star%20Lanes%202-3-05.pdf', '/projects'
        r301 '/storage/project-pages/american%20marine.pdf', '/projects'
        r301 '/storage/project-pages/amish%20store%20rochester%202-2-05.pdf', '/projects'
        r301 '/storage/project-pages/dave%27s%20guitar%20shop.pdf', '/projects'
        r301 '/storage/project-pages/reds%20iga%202-2-05.pdf', '/projects'
        r301 '/storage/project-pages/viroqua%20food%20coop.pdf', '/projects'
        r301 '/storage/Amerhart%20Ltd.%208-17-09.pdf', '/projects'
        r301 '/storage/project-pages/KT%20Commissary.pdf', '/projects'
        r301 '/storage/project-pages/kt%20distribution.pdf', '/projects'
        r301 '/storage/project-pages/kt%20maintenance%202-2-05.pdf', '/projects'
        r301 '/storage/project-pages/r%20%20l%20carriers%20west%20salem%202-2-05.pdf', '/projects'
        r301 '/storage/TriCounty%20Electric%20Coop%201-8-09.pdf', '/projects'
        r301 '/storage/Vernon%20Electric%20Cooperative.pdf', '/projects'
        r301 '/member/wieserbrothers', '/news'
        r301 '/news/trackback/34916600', '/news'
        r301 '/display/ShowJournal?moduleId=751384&creatorId=99363&currentPage=2', '/news'
        r301 '/display/ShowJournal?moduleId=751384&creatorId=99363&currentPage=3', '/news'
        r301 '/news/trackback/34869605', '/news'
        r301 '/news/trackback/34869554', '/news'
        r301 '/news/trackback/34726871', '/news'
        r301 '/news/2014/3/6/safety-award-of-excellence.html', '/news'
        r301 '/news/trackback/34693431', '/news'
        r301 '/news/2014/3/6/superintendentforemanproject-manager-training.html', '/news'
        r301 '/news/2014/3/6/2014-spring-safety-day-training.html', '/news'
        r301 '/news/2014/3/5/wieser-brothers-recognizes-employees-for-thinking-safety.html', '/news'
        r301 '/news/2014/3/4/2014-skill-competition.html', '/news'
        r301 '/news/2014/3/4/recognizing-project-excellence.html', '/news'
        r301 '/news/2013/8/20/wieser-brothers-following-green-practices.html', '/news'
        r301 '/news/2013/4/12/badger-corrugating-ground-breaking-event.html', '/news'
        r301 '/agropur', '/projects'
        r301 '/agropur/october-2014-update/20080139', '/news'
        r301 '/agropur/october-2014-update/20080140', '/news'
        r301 '/agropur/october-2014-update/20098109', '/news'
        r301 '/agropur/september-2014-update/19960303', '/news'
        r301 '/agropur/september-2014-update/19960304', '/news'

    end


    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Custom directories with classes and modules you want to be autoloadable.
    # config.autoload_paths += %W(#{config.root}/extras)

    # Only load the plugins named here, in the order given (default is alphabetical).
    # :all can be used as a placeholder for all plugins not explicitly named.
    # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

    # Activate observers that should always be running.
    # config.active_record.observers = :cacher, :garbage_collector, :forum_observer

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Configure the default encoding used in templates for Ruby 1.9.
    config.encoding = "utf-8"

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Enable escaping HTML in JSON.
    config.active_support.escape_html_entities_in_json = true

    # Use SQL instead of Active Record's schema dumper when creating the database.
    # This is necessary if your schema can't be completely dumped by the schema dumper,
    # like if you have constraints or database-specific column types
    # config.active_record.schema_format = :sql

    # Enforce whitelist mode for mass assignment.
    # This will create an empty whitelist of attributes available for mass-assignment for all models
    # in your app. As such, your models will need to explicitly whitelist or blacklist accessible
    # parameters by using an attr_accessible or attr_protected declaration.
    config.active_record.whitelist_attributes = true

    # Enable the asset pipeline
    config.assets.enabled = true

    # Version of your assets, change this if you want to expire all your assets
    config.assets.version = '1.0'

    config.assets.initialize_on_precompile = false

    config.to_prepare do
        Refinery.searchable_models = [Refinery::Page, Refinery::Projects::Project, Refinery::News::Item, Refinery::Categories::Category]  
    end

  end
end
